// ISO 3166-1 alpha-2 code -> display name. flagcdn uses the same code.
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "pk", name: "Pakistan" },
  { code: "in", name: "India" },
  { code: "bd", name: "Bangladesh" },
  { code: "ar", name: "Argentina" },
  { code: "br", name: "Brazil" },
  { code: "gb-eng", name: "England" },
  { code: "fr", name: "France" },
  { code: "es", name: "Spain" },
  { code: "de", name: "Germany" },
  { code: "pt", name: "Portugal" },
  { code: "nl", name: "Netherlands" },
  { code: "it", name: "Italy" },
  { code: "be", name: "Belgium" },
  { code: "hr", name: "Croatia" },
  { code: "ma", name: "Morocco" },
  { code: "us", name: "United States" },
  { code: "mx", name: "Mexico" },
  { code: "ca", name: "Canada" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "ae", name: "UAE" },
  { code: "qa", name: "Qatar" },
  { code: "ng", name: "Nigeria" },
  { code: "eg", name: "Egypt" },
  { code: "za", name: "South Africa" },
  { code: "sn", name: "Senegal" },
  { code: "gh", name: "Ghana" },
  { code: "dz", name: "Algeria" },
  { code: "tr", name: "Turkey" },
  { code: "ir", name: "Iran" },
  { code: "au", name: "Australia" },
  { code: "co", name: "Colombia" },
  { code: "uy", name: "Uruguay" },
  { code: "lk", name: "Sri Lanka" },
  { code: "np", name: "Nepal" },
  { code: "af", name: "Afghanistan" },
  { code: "id", name: "Indonesia" },
  { code: "my", name: "Malaysia" },
  { code: "ph", name: "Philippines" },
];

export const COUNTRY_NAME = new Map(COUNTRIES.map((c) => [c.code, c.name]));
